require('./app/themes/images/Acura.png');
require('./app/themes/images/Alfa romeo.png');
require('./app/themes/images/Aquarium.png');
require('./app/themes/images/Aston martin.png');
require('./app/themes/images/Audi a6.png');
require('./app/themes/images/Baseball.png');
require('./app/themes/images/Basketball.png');
require('./app/themes/images/Lambo.png');
require('./app/themes/images/Ceed.png');
require('./app/themes/images/Chainsaw.png');
require('./app/themes/images/Chair.png');
require('./app/themes/images/Compass.png');
require('./app/themes/images/Cricket.png');
require('./app/themes/images/Cube.png');
require('./app/themes/images/Football.png');
require('./app/themes/images/GTR.png');
require('./app/themes/images/House.png');
require('./app/themes/images/VIP House.png');
require('./app/themes/images/King chair.png');
require('./app/themes/images/Macbook.png');
require('./app/themes/images/Mazda 6.png');
require('./app/themes/images/Mazda cx5.png');
require('./app/themes/images/Office chair.png');
require('./app/themes/images/PC.png');
require('./app/themes/images/Phone.png');
require('./app/themes/images/Qashqai.png');
require('./app/themes/images/Skateboard.png');
require('./app/themes/images/Sorento.png');
require('./app/themes/images/Stinger.png');
require('./app/themes/images/Table.png');
require('./app/themes/images/Taburet.png');
require('./app/themes/images/TV.png');
require('./app/themes/images/Vaz 2105.png');
require('./app/themes/images/Vaz 2106.png');
require('./app/themes/images/Vaz 2107.png');
require('./app/themes/images/Candy.png');
require('./app/themes/images/Conor.png');
require('./app/themes/images/Dumplings.png');
require('./app/themes/images/Goat.png');
require('./app/themes/images/Samovar.png');
require('./app/themes/images/Whiskey.png');
require('./app/themes/images/Fried chicken.png');
require('./app/themes/images/Vesta White.png');
require('./app/themes/images/Vesta Grey.png');


require('./app/themes/images/homebckg.jpg');
require('./app/themes/images/todobckg.jpg');
require('./app/themes/images/shopbckg.jpg');
require('./app/themes/images/cartbckg.jpg');
